version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: localawskeys1
      AWS_SECRET_ACCESS_KEY: localawskeys2
    depends_on:
      - dynamodb-local

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: localawskeys1
      MINIO_ROOT_PASSWORD: localawskeys2
    command: server --console-address ":9001" /data

  create-replay-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 localawskeys1 localawskeys2;
      /usr/bin/mc mb myminio/local-omd-replay-system-sessions;
      /usr/bin/mc policy set public myminio/local-omd-replay-system-sessions;
      exit 0;
      "

  create-public-mapping-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 localawskeys1 localawskeys2;
      /usr/bin/mc mb myminio/local-omd-public-api-mapping;
      /usr/bin/mc policy set public myminio/local-omd-public-api-mapping;
      exit 0;
      "

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8011:8001'
volumes:
  db:
    driver: local
  minio_storage: { }
