name: Call a reusable workflow

on:
  push:
    branches:
      - dev/*

jobs:  
  call-workflow-passing-data:
    environment: dev
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/workflow-B.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call-test:      
    uses: ./.github/workflows/test.yml