name: Deploy Template

# on:
#   workflow_dispatch:
#     inputs:
#       name:
#         type: choice
#         description: Who to greet
#         options: 
#         - monalisa
#         - cschleiden
#       message:
#         required: true
#       use-emoji:
#         type: boolean
#         description: Include  emojis
#       environment:
#         type: environment

on:
  workflow_call:
    inputs:
      environment:
        type: environment
        description: environment to deploy to
        required: true
      target:
        type: choice
        description: Deployment Target
        options:
          - foo
          - bar
    secrets:
      PASSWORD:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Dump Password
      run: |
        echo Password is $PASSWORD
        if [[ $PASSWORD == *"PROD"* ]]; then
          echo "This is the PROD password!"
        else
          echo "This is NOT the PROD password!"
        fi
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

